### PR TITLE
Validate the rpn expression before eval

### LINKED ISSUE #41: Invalid expressions give results
Invalid expressions give results, e.g.:  “12 18 2” = 2. or “(12)(18)” = 18.
Instead, an exception should be thrown.

### PR DESCRIPTION
**Pull request by luis451**
Fixed #41

### CODE REVIEW

**Comment by squeek502** [comment]
It would probably be better to move the `validate()` call to either the constructor or after the `shuntingYard()` call in `getRPN()`. Calling `validate` each `eval` is overkill since the RPN is constant per `Expression` instance, and it would cut into the benefits of #3.

**Comment by uklimaschewski** [comment]
First of all, thank you luis for this code - looks like an easy and quick validation feature.
But I agree with Ryan that this should not be called on each evaluation.
You can place it here:
````java
	private List<String> getRPN() {
		if (rpn == null) {
			rpn = shuntingYard(this.expression);
			validate(rpn); // only called once for each expression
		}
		return rpn;
	}
````

**Comment by luis451** [comment]
Updated with those changes.
 I moved `validate()` after the `shuntingYard()` call in `getRPN()`

**Comment by uklimaschewski** [comment]
This may sound like nitpicking, but I am unhappy with the getRPN() call in validate(), this looks odd, because validate() is called from getRPN().
Could you just pass the rpn instance as a parameter to the validate() method and use it there in the for-loop?
This will look much cleaner.

**Comment by luis451** [comment]
I added parameter to `validate()`, also i make `validate()` private since `getRPN()` is private and is te only way to get the rpn notation. As well being private there a no reason to `validate()` to return  `this`

**Comment by uklimaschewski** [comment]
Ok, thank you again :+1:

**Comment by squeek502** [comment]
Very cool. :+1:

**Pull request merged**
