### PR TITLE
made Variable,Functions,Operator case insensitive, Added getters for declre

### PR DESCRIPTION
**Pull request by fobbyal**
I am working on a project that is going to be using ExVal extensively. The following features are going to make my life much easier. 
 
Made Variable,Functions,Operator case insensitive,
Added getters (Unmodifiable) for declared variables, functions and operators.

All original plus case insensitive tests are passing

### CODE REVIEW

**Comment by uklimaschewski** [comment]
I'll have a look on it on the weeken.
Please check the unit tests - System.out.println() is not an assertion! ;-)

**Comment by fobbyal** [comment]
Sorry, I'll go and correct those. I forgot to finish them.

**Comment by fobbyal** [comment]
There is also something that i would like to modification but want your opinion.

I want to make addVariable(String,BigDecimal) into addVariabl(String,Number) 
it will basically look at the implementation of the Number and normalize them into BigDecimal. Do you think that is appropriate here?

**Comment by squeek502** [comment]
Are case-insensitive variables a good thing? I can see the usefulness for functions, but variables seem a bit questionable.

**Comment by uklimaschewski** [comment]
If functions are case insensitive, then why not also variables?

**Comment by squeek502** [comment]
For some reason it strikes me as odd, although I don't have many good reasons for that. I guess it's not a big deal.

**Comment by fobbyal** [comment]
I've added the proper tests for the new getters. Let me know how the it looks.

**Comment by uklimaschewski** [comment]
Alex, I have a problem with your pull request.
It looks like you have changed the import section (`import java.util.*`) and reformatted the code.
Please do not reformat the code, a diff now shows every line of code as a change.
This makes tracking of changes nearly impossible.
Also, please leave the .project line in the .gitignore.

**Comment by fobbyal** [comment]
sorry about that.. let me close this request and redo my work. I'll submit a new PR.

**Pull request closed without merging**
