### PR TITLE
Fix isNumber check for empty strings

### PR DESCRIPTION
**Pull request by ssheikin**

### CODE REVIEW

**Comment by uklimaschewski** [comment]
merged this, thanks!

**Comment by ssheikin** [comment]
Thank you for merging!
Could I ask for a new release with this fix? 
It will allow to compare empty strings with `STREQ` from the example.

**Comment by uklimaschewski** [comment]
When #270 is working, I will make a release

**Comment by RobertZenz** [comment]
As a sidenote, swapping the two checks would have had the same effect:

```java
if (st.length() == 1 && st.charAt(0) == MINUS_SIGN) {
```

**Comment by uklimaschewski** [comment]
@ssheikin I just created version 2.7. Might take a while, until it pops up in Maven Central.

**Pull request merged**
