### PR TITLE
Fix for #244

### PR DESCRIPTION
**Pull request by SirError**
The fix follows what was suggested by the issue creator

### CODE REVIEW

**Comment by uklimaschewski** [comment]
Please do not reformat the code and do not change the import order.
Can you undo the reformat and submit again?

**Comment by SirError** [comment]
> 
> 
> Please do not reformat the code and do not change the import order.
> Can you undo the reformat and submit again?

Done :)
thanks!

**Comment by SirError** [comment]
Hi, sorry to bother you

Could you please consider merging this fix?

thanks!

**Comment by uklimaschewski** [comment]
Hi, sorry for the delay. I will have a look at it the next days. Promised.

**Comment by uklimaschewski** [comment]
I had to change your unit test, as it was using some Java 8 classes.
I also squashed all the commits to a single one and merged it using PR #258.
Thanks for the fix and sorry again for the delay.

**Pull request closed without merging**
