### PR TITLE
Added Summation (SIGMA)

### PR DESCRIPTION
**Pull request by MrMaurice211**

### CODE REVIEW

**Comment by uklimaschewski** [comment]
Sorry for the delay, but is this of any general use? Apart of that it is missing proper documentation of what it does exactly, I see no need to put this specialized function to the standard library of functions.

**Comment by MrMaurice211** [comment]
> Sorry for the delay, but is this of any general use? Apart of that it is missing proper documentation of what it does exactly, I see no need to put this specialized function to the standard library of functions.

Well is just another arithmetical expression which i think can fit pretty well, this is the one:

https://en.wikipedia.org/wiki/Summation

**Comment by RobertZenz** [comment]
Here's a unittest and documentation missing, so that we can see the usecase.

**Comment by MrMaurice211** [comment]
Currently not working, incompatible with the current variable detection system, thanks for looking at it!

**Pull request closed without merging**
