### PR TITLE
Added Radian option for trigonometric functions

### LINKED ISSUE #206: Extra methods for Radian and Gradian
Great library, it would be awesome to also calculate sin, cos, tang, etc for Radian and Gradian too. which we can find the answer for sinr(pi) or etc without converting all the time.
here are some methods: (sinr = sinRadian, sing = singradian)

```Java
// Sin Radian
        addFunction(new Function("SINR", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = Math.sin(parameters.get(0).doubleValue());
                return new BigDecimal(d, mc);
            }
        });
        // Cos Radian
        addFunction(new Function("COSR", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = Math.cos(parameters.get(0).doubleValue());
                return new BigDecimal(d, mc);
            }
        });
        // Tan Radian
        addFunction(new Function("TANR", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = Math.tan(parameters.get(0).doubleValue());
                return new BigDecimal(d, mc);
            }
        });
        // Sec Radian
        addFunction(new Function("SECR", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = 1.0 / Math.cos(parameters.get(0).doubleValue());
                return new BigDecimal(d, mc);
            }
        });
        // Csc Radian
        addFunction(new Function("CSCR", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = 1.0 / Math.sin(parameters.get(0).doubleValue());
                return new BigDecimal(d, mc);
            }
        });
        // Cot Radian
        addFunction(new Function("COTR", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = 1.0 / Math.tan(parameters.get(0).doubleValue());
                return new BigDecimal(d, mc);
            }
        });
        // Sin Gradian
        addFunction(new Function("SING", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = Math.sin(Convertor.Angle.gradiansToRadians(parameters.get(0)).doubleValue());
                return new BigDecimal(d, mc);
            }
        });
        // Cos Gradian
        addFunction(new Function("COSG", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = Math.cos(Convertor.Angle.gradiansToRadians(parameters.get(0)).doubleValue());
                return new BigDecimal(d, mc);
            }
        });
        // Tan Gradian
        addFunction(new Function("TANG", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = Math.tan(Convertor.Angle.gradiansToRadians(parameters.get(0)).doubleValue());
                return new BigDecimal(d, mc);
            }
        });
        // Sec Gradian
        addFunction(new Function("SECG", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = 1.0 / Math.cos(Convertor.Angle.gradiansToRadians(parameters.get(0)).doubleValue());
                return new BigDecimal(d, mc);
            }
        });
        // Csc Gradian
        addFunction(new Function("CSCG", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = 1.0 / Math.sin(Convertor.Angle.gradiansToRadians(parameters.get(0)).doubleValue());
                return new BigDecimal(d, mc);
            }
        });
        // Cot Gradian
        addFunction(new Function("COTG", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = 1.0 / Math.tan(Convertor.Angle.gradiansToRadians(parameters.get(0)).doubleValue());
                return new BigDecimal(d, mc);
            }
        });
        // aSin Radian
        addFunction(new Function("ASINR", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = Math.asin(parameters.get(0).doubleValue());
                return new BigDecimal(d, mc);
            }
        });
        // aCos Radian
        addFunction(new Function("ACOSR", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = Math.acos(parameters.get(0).doubleValue());
                return new BigDecimal(d, mc);
            }
        });
        // aTan Radian
        addFunction(new Function("ATANR", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = Math.atan(parameters.get(0).doubleValue());
                return new BigDecimal(d, mc);
            }
        });
        // aSec Radian
        addFunction(new Function("ASECR", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = Math.acos(1.0 / parameters.get(0).doubleValue());
                return new BigDecimal(d, mc);
            }
        });
        // aCsc Radian
        addFunction(new Function("ACSCR", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = Math.asin(1.0 / parameters.get(0).doubleValue());
                return new BigDecimal(d, mc);
            }
        });
        // aCot Radian
        addFunction(new Function("ACOTR", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = Math.atan(1.0 / parameters.get(0).doubleValue());
                return new BigDecimal(d, mc);
            }
        });
        // aSin Gradian
        addFunction(new Function("ASING", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = Double.valueOf(Convertor.Angle.radiansToGradians(new BigDecimal(Math.asin(parameters.get(0).doubleValue()))).toString());
                return new BigDecimal(d, mc);
            }
        });
        // aCos Gradian
        addFunction(new Function("ACOSG", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = Double.valueOf(Convertor.Angle.radiansToGradians(new BigDecimal(Math.acos(parameters.get(0).doubleValue()))).toString());
                return new BigDecimal(d, mc);
            }
        });
        // aTan Gradian
        addFunction(new Function("ATANG", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = Double.valueOf(Convertor.Angle.radiansToGradians(new BigDecimal(Math.atan(parameters.get(0).doubleValue()))).toString());
                return new BigDecimal(d, mc);
            }
        });
        // aSec Gradian
        addFunction(new Function("ASECG", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = Double.valueOf(Convertor.Angle.radiansToGradians(new BigDecimal(Math.acos(1.0 / parameters.get(0).doubleValue()))).toString());
                return new BigDecimal(d, mc);
            }
        });
        // aCsc Gradian
        addFunction(new Function("ACSCG", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = Double.valueOf(Convertor.Angle.radiansToGradians(new BigDecimal(Math.asin(1.0 / parameters.get(0).doubleValue()))).toString());
                return new BigDecimal(d, mc);
            }
        });
        // aCot Gradian
        addFunction(new Function("ACOTG", 1)
        {
            @Override
            public BigDecimal eval(List<BigDecimal> parameters)
            {
                double d = Double.valueOf(Convertor.Angle.radiansToGradians(new BigDecimal(Math.atan(1.0 / parameters.get(0).doubleValue()))).toString());
                return new BigDecimal(d, mc);
            }
        });
```

### PR DESCRIPTION
**Pull request by NumberC**
Fixes #206 
Before you could only do SIN(90) and it would return 1. You could only use degrees with trigonometric functions. Now, you can also use radians, so SINR(pi/2) will also return 1. I added documentation as well.

### CODE REVIEW

**Comment by NumberC** [comment]
@uklimaschewski Can you please merge this? If not, can you specifiy why? I checked the Travis CI error and it doesn't seem to be related to my changes.

**Comment by uklimaschewski** [comment]
Sorry for the failures in build, I manually retried a few times.
Unit tests are OK, but Travis seems to have a problem connecting to Sonar.
Your PR looks ok for me, please have patience while I try to figure out what is going wrong between Travis and Sonar.

**Comment by NumberC** [comment]
@uklimaschewski Ok. Thank you! Good luck fixing the Travis and Sonar errors!

**Comment by uklimaschewski** [comment]
I hope I have sorted out the Sonar problems with the latest commit.
Can please rebase your code and submit the PR again?

**Comment by NumberC** [comment]
@uklimaschewski Is this better?

**Comment by NumberC** [comment]
I'm not sure what's wrong.

**Comment by uklimaschewski** [comment]
OK, I made another change to the .travis.yml.
Can you rabase again, to fetch the change and submit the PR gain?

**Comment by NumberC** [comment]
Still the same error

**Comment by uklimaschewski** [comment]
I merged this, despite the sonar problems. Seems to be a genarl problem with external pull requests.
If anybody knows a working travis/sonar configuration, that also works for external pull request, please speak up!

**Comment by uklimaschewski** [comment]
For the record, it looks like for external pull requests, the sonar addon in travis is not called, thus leaving the sonar setup unconfigured.

**Pull request merged**
