### PR TITLE
add finals, general code cleanup

### PR DESCRIPTION
**Pull request by barnhill**
Adding finals to variables and places that it can be to more clearly denote what should be modified and what shouldnt.  Also allows for more compilation optimization.

Some general code cleanup as suggested by intelliJ to prevent coding errors in the future (ex. methods and if statement blocks that have no brackets)

### CODE REVIEW

**Comment by uklimaschewski** [comment]
Thank you, but after a quick test, I see no performance enhancements resulting from the extensive use of the `final` keywword in the code.

Using `final` in method parameters is also of very limited use and practically not needed here. (IMHO)

Pull requests should either enhance the performance or functionality of this library.

**Comment by barnhill** [comment]
http://www.javapractices.com/topic/TopicAction.do?Id=23

**Comment by barnhill** [comment]
http://stackoverflow.com/questions/137868/using-final-modifier-whenever-applicable-in-java

**Comment by uklimaschewski** [comment]
As I noted, this is all about coding practices. And I don't want to start a war on what is the best coding practice.
It has no influence on performance or functionality.

**Comment by barnhill** [comment]
It was less about performance and more about clarity on those variables and their intention of not being set to another instance.  Its fine it works as is.  I was just going for cleaner, more concise and clear coding intentions on the variable declarations.  Its your lib and you make the ultimate decision.  Just trying to help out.  Keep up the good work on it.

**Pull request closed without merging**
