### PR TITLE
Added FACT(expr) function. Fixed AbstractOperator and AbstractUnaryOp…

### PR DESCRIPTION
**Pull request by DesigningKnights**
…erator with final for LazyNumber.

Redid the commit and got rid of all the mess in the diffs.

### CODE REVIEW

**Comment by RobertZenz** [comment]
Thank you very much, that is a lot easier to review.

There are still the two `final`s changes which seem superfluous.

@uklimaschewski With the exception of the `final`s being added, looks good to me. The implementation is a little bit "naive", as in there are [faster implementations available](http://www.luschny.de/math/factorial/FastFactorialFunctions.htm), but this seems okay to me, especially as the user still has the ability to override this with their own implementation, if needed (and if they already have their own, this will not impact them).

**Comment by DesigningKnights** [comment]
IDEA threw an error saying that the finals are required as they are accessed from in an inner class, refused to compile without them."Variable v1 is accessed from within inner class, needs to be declared final". is the exact message.  
error final

**Comment by DesigningKnights** [comment]
As for the algorithm, I went for the simplest method, avoiding recursion. I don't like recursion because it can quickly cause an out of memory error, especially if someone tries to do something like FACT(1000).

**Comment by wxisme** [comment]
@DesigningKnights I think you should create a new branch to submit your PR instead of modifying the master branch directly. In addition I have submitted another PR(#176) specifically to solve the problem of `finals`.
@RobertZenz

**Pull request merged**
